# Generated by Django 4.2.9 on 2024-03-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0002_acquistion_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acquistion",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="acquistionpage",
            name="investor",
        ),
    ]
