# Generated by Django 4.2.9 on 2024-03-17 21:59

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0004_alter_acquistiontag_content_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acquistiontag",
            name="content_object",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aquisition_tags",
                to="investments.acquistionpage",
            ),
        ),
    ]
