# Generated by Django 4.2.9 on 2024-03-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0005_alter_acquistiontag_content_object"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acquistionpage",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="acquistionpage",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
