# Generated by Django 4.2.9 on 2024-03-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0002_strategypage_tab_four_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategypage",
            name="tab_four_title",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="tab_one_title",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="tab_three_title",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="strategypage",
            name="tab_two_title",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
