# Generated by Django 4.2.9 on 2024-03-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a page to link to when the CTA button in the hero section is clicked.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Call-to-Action Link",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta_text",
            field=models.CharField(
                blank=True,
                help_text="Enter the text to display on the Call-to-Action (CTA) button in the hero section.",
                max_length=255,
                null=True,
                verbose_name=" Call-to-Action Text",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_heading_one",
            field=models.CharField(
                blank=True,
                help_text="Provide a descriptive heading for the hero section that introduces and summarizes the business.",
                max_length=255,
                null=True,
                verbose_name="Hero Heading",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_heading_two",
            field=models.CharField(
                blank=True,
                help_text="Provide a descriptive heading for the hero section that introduces and summarizes the business.",
                max_length=255,
                null=True,
                verbose_name="Hero Heading",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose an image to visually represent the hero section, capturing attention and conveying the essence of the business.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Hero Image",
            ),
        ),
    ]
