# Generated by Django 4.2.9 on 2024-03-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investment", "0002_acquisition_a_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investor",
            options={"verbose_name": "Acquirer", "verbose_name_plural": "Acquirers"},
        ),
    ]
