# Generated by Django 4.2.9 on 2024-03-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="heading",
            field=models.CharField(
                blank=True,
                help_text='Add a subtitle for this page. Example: "About Scopio Holding".',
                max_length=100,
                null=True,
                verbose_name="Subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Upload an image to be displayed within the first tab.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
