# Generated by Django 4.2.9 on 2024-03-21 14:20

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("advisors", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisor",
            name="bio",
            field=wagtail.fields.RichTextField(blank=True, max_length=300),
        ),
    ]
