# Generated by Django 4.2.9 on 2024-03-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advisors", "0003_advisor_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisor",
            name="role",
            field=models.CharField(
                blank=True, max_length=254, null=True, verbose_name="Role"
            ),
        ),
    ]
